[package]
name = "nightingale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc16 = "0.4.0"
mavlink = "0.12.0"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
tokio-stream = "0.1.14"
tokio-util = { version = "0.7.10", features = ["codec"] }
