[package]
name = "nightingale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
bytes = "1.5.0"
mavlink = "0.12.0"
tokio = { version = "1.33.0", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time"] }
tokio-util = "0.7.10"
