[package]
name = "nightingale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mavlink = "0.12.0"
tokio = { version  = "1.33.0", features = ["rt-multi-thread", "macros", "net", "io-util"]}
